In [1]:
import numpy as np
from scipy.special import expit

In [40]:
X = np.random.normal(loc=0.0, 
                     scale = 0.1, 
                     size = 10000).reshape(1000, 10)

In [41]:
X.shape

(1000, 10)

In [42]:
coef_ = np.random.random(10)
intercept_ = 0.20

In [43]:
preds = X.dot(coef_) + intercept_
preds

array([ 0.62363424,  0.24480087,  0.07097286,  0.12529373,  0.11509895,
        0.30023589,  0.2187935 ,  0.42167547,  0.25993064,  0.199608  ,
       -0.04131368,  0.14109394,  0.2962639 ,  0.20629395,  0.12694733,
        0.12107266,  0.0830135 ,  0.45197697,  0.21045158,  0.09336927,
        0.07130015,  0.33868818, -0.06960522,  0.11002402,  0.03817545,
        0.42320536,  0.38743756, -0.11742571,  0.35342963, -0.06939191,
        0.23602519,  0.51291101,  0.29941657,  0.08686559,  0.17912856,
        0.45752993,  0.27563339,  0.18439667,  0.04565162,  0.2464578 ,
        0.72430879,  0.20871486, -0.06296186,  0.43027069,  0.03378374,
        0.17065303,  0.1071836 ,  0.36856058,  0.31664772, -0.13651458,
        0.27531286, -0.02206491,  0.35070649,  0.13969288,  0.23344124,
        0.29905483,  0.36969301,  0.0814391 ,  0.31277782,  0.48188628,
        0.0379761 ,  0.12791589,  0.02709272,  0.24850919,  0.26269539,
        0.25344474,  0.27189302,  0.53659306,  0.17094956,  0.06

In [17]:
preds.shape

(1000,)

In [18]:
coef_ = np.random.random(20).reshape(10,2)
coef_

array([[0.13653178, 0.56800241],
       [0.03258015, 0.06709481],
       [0.82464078, 0.97776825],
       [0.80697826, 0.13566638],
       [0.25548628, 0.92086752],
       [0.34381013, 0.53685996],
       [0.5161407 , 0.85878756],
       [0.84975718, 0.91541007],
       [0.19948109, 0.37878647],
       [0.12096783, 0.07891376]])

In [19]:
preds = X.dot(coef_) + intercept_
preds

array([[ 0.3437616 ,  0.2761514 ],
       [-0.08691299, -0.10666448],
       [ 0.0336867 ,  0.01422881],
       ...,
       [-0.05809299,  0.08647921],
       [ 0.21438928,  0.24778046],
       [ 0.49332095,  0.3422108 ]])

In [20]:
preds.shape

(1000, 2)

In [44]:
coef_ = np.random.random(30).reshape(10,3)
preds = X.dot(coef_) + intercept_
preds.shape

(1000, 3)

In [45]:
hidden_output = np.maximum(0, preds)
hidden_output[:20]

array([[0.46151617, 0.30860914, 0.33954796],
       [0.37408081, 0.28313029, 0.25450425],
       [0.20302212, 0.09271274, 0.22089895],
       [0.29723421, 0.30239538, 0.22367855],
       [0.10088462, 0.03195817, 0.03313929],
       [0.24392189, 0.46124105, 0.19589312],
       [0.17839303, 0.29692891, 0.3199931 ],
       [0.32904653, 0.51489089, 0.12717647],
       [0.48705516, 0.31226974, 0.26210474],
       [0.30347303, 0.18210546, 0.24132112],
       [0.12447665, 0.02363473, 0.24938704],
       [0.10852846, 0.12397659, 0.28581668],
       [0.28781343, 0.33906889, 0.27852968],
       [0.13165365, 0.23779684, 0.09801182],
       [0.        , 0.15443406, 0.20007464],
       [0.270383  , 0.        , 0.39956796],
       [0.06908208, 0.42117631, 0.        ],
       [0.48164122, 0.15771499, 0.35959369],
       [0.23208138, 0.21938205, 0.18596852],
       [0.21421469, 0.04535003, 0.26068884]])

In [46]:
output_coef_ = np.random.normal(0, 0.1, 6).reshape(3, 2)

In [47]:
output_coef_

array([[-0.18431198, -0.13139555],
       [-0.00384739,  0.03853247],
       [-0.04767469, -0.04955172]])

In [48]:
final_output = hidden_output.dot(output_coef_)
final_output

array([[-0.10243814, -0.06557489],
       [-0.0821703 , -0.05085397],
       [-0.0483074 , -0.03404968],
       ...,
       [-0.00341655, -0.00256063],
       [-0.00756614, -0.00603085],
       [-0.07735836, -0.04833122]])

In [49]:
final_output.shape

(1000, 2)

In [50]:
predict_proba = expit(final_output)

In [51]:
predict_proba[:10]

array([[0.47441284, 0.48361215],
       [0.47946898, 0.48728925],
       [0.4879255 , 0.4914884 ],
       [0.48335339, 0.49037947],
       [0.4949259 , 0.49658344],
       [0.48598581, 0.4940042 ],
       [0.48768301, 0.49303674],
       [0.48283392, 0.49257628],
       [0.47415623, 0.48376768],
       [0.48297177, 0.4887979 ]])

In [52]:
final_predictions = np.argmax(predict_proba, axis = 1)

In [53]:
final_predictions

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,